name: GitLab CE # Name of the Catalog Entry
description: |
  > Source control system
version: 0.1 # Version of the Catalog to be used
category: Development # Category to be used for searching catalog entries
maintainer: Taras Omelianenko <t.omelianenko@apibest.com> # The maintainer of the catalog entry
license: MIT
projectURL: https://github.com/apibest/rancher-catalog/tree/master/templates/gitla
